plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/lakshmeshwarpandey/sulaksh-website"
publishOrigin = "config"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]