services:
  - type: web
    name: sulaksh-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://sulaksh.netlify.app
      - key: JWT_SECRET
        sync: false
      - key: STORAGE_ACCESS_KEY_ID
        sync: false
      - key: STORAGE_SECRET_ACCESS_KEY
        sync: false
      - key: STORAGE_ENDPOINT
        value: https://s3.ca-east-006.backblazeb2.com
      - key: STORAGE_REGION
        value: ca-east-006
      - key: STORAGE_BUCKET
        value: sulaksh-materials
